import { Contact } from "@/app/(private)/(user)/contact/types";

export const sampleContacts: Contact[] = [
  {
    id: "1",
    name: "John Doe",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "Hey, how are you doing?",
    timestamp: "10:30 AM",
    unread: 2,
    status: "online",
    messages: [
      {
        id: "m1",
        content: "Hey there!",
        timestamp: "10:15 AM",
        sender: "them",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m2",
        content: "How's it going?",
        timestamp: "10:16 AM",
        sender: "them",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m3",
        content: "I'm doing well, thanks for asking!",
        timestamp: "10:18 AM",
        sender: "me",
        status: "delivered",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m4",
        content: "Hey, how are you doing?",
        timestamp: "10:30 AM",
        sender: "them",
        status: "delivered",
        date: "",
        messageTimestamp: 0,
      },
    ],
  },
  {
    id: "2",
    name: "Jane Smith",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "Can we meet tomorrow?",
    timestamp: "9:45 AM",
    unread: 0,
    status: "online",
    messages: [
      {
        id: "m1",
        content: "Hi Jane!",
        timestamp: "9:30 AM",
        sender: "me",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m2",
        content: "Hello! How are you?",
        timestamp: "9:32 AM",
        sender: "them",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m3",
        content: "I'm good. Are you free tomorrow?",
        timestamp: "9:35 AM",
        sender: "me",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m4",
        content: "Can we meet tomorrow?",
        timestamp: "9:45 AM",
        sender: "them",
        status: "delivered",
        date: "",
        messageTimestamp: 0,
      },
    ],
  },
  {
    id: "3",
    name: "Work Group",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "Meeting at 3 PM",
    timestamp: "Yesterday",
    unread: 5,
    isGroup: true,
    status: "",
    messages: [
      {
        id: "m1",
        content: "Team, we need to discuss the project timeline",
        timestamp: "Yesterday, 2:30 PM",
        sender: "them",
        senderName: "Alex",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m2",
        content: "I'll be available after 3",
        timestamp: "Yesterday, 2:35 PM",
        sender: "them",
        senderName: "Maria",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m3",
        content: "Works for me",
        timestamp: "Yesterday, 2:40 PM",
        sender: "me",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m4",
        content: "Meeting at 3 PM",
        timestamp: "Yesterday, 2:45 PM",
        sender: "them",
        senderName: "Alex",
        status: "delivered",
        date: "",
        messageTimestamp: 0,
      },
    ],
  },
  {
    id: "4",
    name: "Mom",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "Call me when you're free",
    timestamp: "Yesterday",
    unread: 0,
    status: "offline",
    messages: [
      {
        id: "m1",
        content: "Hi dear, how are you?",
        timestamp: "Yesterday, 5:30 PM",
        sender: "them",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m2",
        content: "I'm good Mom, just busy with work",
        timestamp: "Yesterday, 6:00 PM",
        sender: "me",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m3",
        content: "Call me when you're free",
        timestamp: "Yesterday, 6:05 PM",
        sender: "them",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
    ],
  },
  {
    id: "5",
    name: "David Wilson",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "The documents are ready",
    timestamp: "Monday",
    unread: 0,
    status: "offline",
    messages: [
      {
        id: "m1",
        content: "Have you prepared the documents?",
        timestamp: "Monday, 11:30 AM",
        sender: "me",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m2",
        content: "Working on them now",
        timestamp: "Monday, 12:00 PM",
        sender: "them",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
      {
        id: "m3",
        content: "The documents are ready",
        timestamp: "Monday, 4:45 PM",
        sender: "them",
        status: "read",
        date: "",
        messageTimestamp: 0,
      },
    ],
  },
];
