### Get assistants
POST https://solvus.io/api/rest/assistantsAdmin
Content-Type: application/json

{
  "Authorization": "Bearer "
}

### Get assistants
POST https://solvus.io/api/rest/upload/dana
Content-Type: application/json

{
  "Authorization": "Bearer "
}