### Need to use REST CLIENT EXTENSION
POST http://app.solvus.io/rest/login
Content-Type: application/json

{
  "email": "dana@gmail.com",
  "senha": "123456"
}

### Need to use REST CLIENT EXTENSION
POST http://app.solvus.io/rest/dashboard
Content-Type: application/json

{
  "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDY3MzcwNzYsImV4cCI6MTc0Njc0MDY3NiwidWlkIjoiMTMiLCJlbWFpbCI6ImRhbmFAZ21haWwuY29tIiwibm9tZSI6IkRhbmEifQ.CTT0X_vh3QaJexmUlg4T58ohpEZDPzHPAz31w_fmT1Q"
}