### Need to use REST CLIENT EXTENSION
POST https://solvus.io/api/rest/login
Content-Type: application/json

{
  "email": "dana@gmail.com",
  "senha": "123456"
}

### Need to use REST CLIENT EXTENSION
POST https://solvus.io/api/rest/dashboard
Content-Type: application/json

{
  "Authorization": "Bearer"
}

### Get assistants
POST https://app.solvus.io/rest/assistants
Content-Type: application/json

{
  "Authorization": "Bearer",
  "startDate": "2025-05-09",
  "endDate": "2025-05-11"
}


### Get Profile
POST https://app.solvus.io/rest/profile
Content-Type: application/json

{
  "Authorization": "Bearer"
}

### Update Profile
PUT https://app.solvus.io/rest/profile
Content-Type: application/json

{
  "Authorization": "Bearer",
  "nome": "Equipe Dana" 
}

### Get Chat 
POST https://app.solvus.io/rest/getChat
Content-Type: application/json

{
  "Authorization": "Bearer",
  "remoteJid" : "559183191259@s.whatsapp.net"
}

### Get Leads 
POST https://solvus.io/api/rest/leads?q=ju
Content-Type: application/json

{
  "Authorization": "Bearer"
}

### Get History 
POST https://solvus.io/api/rest/history
Content-Type: application/json

{
  "Authorization": "Bearer"
}

### Get History 
POST https://solvus.io/api/rest/getAssistant
Content-Type: application/json

{
  "Authorization": "Bearer",
  "id" : "id do assistente",
}

### Get Assistant 
POST https://solvus.io/api/rest/historyChat
Content-Type: application/json

{
  "Authorization": "Bearer",
  "thread_id" : "thread_id"
}


### Get Guest Assistant
POST https://solvus.io/api/rest/getGuestAssistant
Content-Type: application/json

{
  "assistente" : "fortbras"
}
