###
POST https://solvus.io/api/rest/campaigns
Content-Type: application/json

{
  "Authorization" : "Bearer "
}

###
POST https://solvus.io/api/rest/campaigns
Content-Type: application/json

{
  "Authorization" : "Bearer "
}